BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Users` (
	`UID`	TEXT NOT NULL UNIQUE,
	`Name`	TEXT NOT NULL,
	`Subscription`	INTEGER NOT NULL,
	`LastAccess`	INTEGER DEFAULT NULL,
	PRIMARY KEY(`UID`)
);
CREATE TABLE IF NOT EXISTS `Feeds` (
	`UID`	TEXT NOT NULL,
	`MID`	TEXT NOT NULL,
	`Meal`	TEXT DEFAULT NULL
);
COMMIT;
